############# German navigation ##############

# main menu
[[main]]
name = "Start"
pageRef = "/"
weight = 1

[[main]]
name = "Über uns"
pageRef = "/about"
weight = 2

[[main]]
name = "Mitgliedschaft"
pageRef = "/elements"
weight = 3

[[main]]
name = "Museen"
pageRef = "/elements"
weight = 4

[[main]]
weight = 4
name = "Pages"

[[main]]
parent = "Pages"
name = "Blog"
pageRef = "/blog"

[[main]]
parent = "Pages"
name = "Contact"
pageRef = "/contact"

[[main]]
parent = "Pages"
name = "Authors"
pageRef = "/authors"

[[main]]
parent = "Pages"
name = "Categories"
pageRef = "/categories"

[[main]]
parent = "Pages"
name = "404 Page"
pageRef = "/404"


# footer menu
[[footer]]
name = "Impressum"
pageRef = "/about"
weight = 1

[[footer]]
name = "Datenschutz"
pageRef = "/elements"
weight = 2

